apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-api
spec:
  replicas: 2 # Number of replicas to run
  selector:
    matchLabels:
      app: messages-api
  template:
    metadata:
      labels:
        app: messages-api
    spec:
      containers:
      - name: messages-api
        image: rossetow/messages-api:4.0 # Image name
        env:
          - name: MYSQL_HOST
            value: "mysql"             # Matches MySQL Service name
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_DATABASE
            value: "Messages"
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-secret
                key: mysql-user
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-secret
                key: mysql-password
        ports:
        - containerPort: 5050


---
apiVersion: v1
kind: Service
metadata:
  name: messages-service
spec:
  type: NodePort
  selector:
    app: messages-api
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30150