services:
  # Serviço da API (Node.js com TypeScript)
  api:
      build:
        context: ./api
      container_name: messages-api
      ports:
        - "5050:5050"
      environment:
        MYSQL_HOST: db
        MYSQL_PASSWORD: root
        MYSQL_USER: root
        MYSQL_DATABASE: Messages
      depends_on:
        - db
      networks:
        - app-network

  # Serviço do Frontend (React.js)
  frontend:
      build:
        context: ./client
      container_name: messages-frontend
      ports:
        - "3000:3000"
      environment:
        NODE_APP_API_URL: "http://api:5050"  # URL da API
      depends_on:
        - api
      networks:
        - app-network

  # Serviço do Banco de Dados (MySQL)
  db:
      # image: rossetow/messages-db:2.0
      build:
        context: ./db
      container_name: db
      environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: Messages
      ports:
        - "3305:3306"
      networks:
        - app-network
      volumes:
        - db-data:/var/lib/mysql

# Redes
networks:
  app-network:
    driver: bridge

# Volumes para persistência de dados do banco
volumes:
  db-data:
